name: Merge ICU upstream changes

on:
  push:
    branches:
      - master

jobs:
  merge-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Merge upstream changes
        run: |
          git config --global user.email "chetan.laddga@gmail.com"
          git config --global user.name "Bot Auto Commit"
          git remote add upstream https://github.com/unicode-org/icu.git
          git fetch upstream
          git merge --allow-unrelated-histories --strategy-option=theirs upstream/main || true
          
          git add icu4c
          git commit -m "Adding latest changes"
          git push
        continue-on-error: true
